name: env_vars

on:
 push:
   branches: [ main ]
jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v4
   - name: Create Firestore Service Account File
     env:
       FIRESTORE_SERVICE_ACCOUNT: ${{ secrets.FIRESTORE_SERVICE_ACCOUNT }}
     run: |
       echo "$FIRESTORE_SERVICE_ACCOUNT" > firestore-service-account.json
       echo "GOOGLE_APPLICATION_CREDENTIALS=firestore-service-account.json" >> $GITHUB_ENV